authentication:
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: 'GET "/" "HTTP/1.1\r\nHost: splat.dev"'
    healthy_threshold: 2
    response_timeout: 2000

circulation:
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: 'GET "/" "HTTP/1.1\r\nHost: splat.dev"'
    healthy_threshold: 2
    response_timeout: 2000

config:
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: 'GET "/" "HTTP/1.1\r\nHost: splat.dev"'
    healthy_threshold: 2
    response_timeout: 2000

frontend:
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: 'GET "/" "HTTP/1.1\r\nHost: splat.dev"'
    healthy_threshold: 2
    response_timeout: 2000

metadata:
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: 'GET "/" "HTTP/1.1\r\nHost: splat.dev"'
    healthy_threshold: 2
    response_timeout: 2000

patron:
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: 'GET "/" "HTTP/1.1\r\nHost: splat.dev"'
    healthy_threshold: 2
    response_timeout: 2000

skynet:
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: 'GET "/" "HTTP/1.1\r\nHost: splat.dev"'
    healthy_threshold: 2
    response_timeout: 2000

work:
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: 'GET "/" "HTTP/1.1\r\nHost: splat.dev"'
    healthy_threshold: 2
    response_timeout: 2000

