name: Quria  
description: >
  Quria is a cloud-based, digital-first Library Services Platform,
  designed to facilitate the transformation of the modern public
  library. It’s unique in how it supports library staff, making daily
  work routines more efficient, dramatically reducing the number of
  systems that staff need access to, and providing a complete overview
  of what is happening in the library.
version: quria-0
category: "Applications"
